version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: tienda-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_NAME:-tienda_db}
      MYSQL_USER: ${DB_USERNAME:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    container_name: tienda-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-tienda_db}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      JWT_SECRET: ${JWT_SECRET:-your-very-long-secret-key}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:5173}
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN:-your-test-token}
      MP_PUBLIC_KEY: ${MP_PUBLIC_KEY:-your-public-key}
      UPLOAD_DIR: /uploads
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - uploads:/uploads
    restart: unless-stopped
volumes:
  db_data:
  uploads: